project:
  type: default

format:
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    linkcolor: blue
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=3cm
      - right=3cm
    header-includes:
      - \usepackage{fancyhdr}
      - \pagestyle{fancy}
      - \fancyhead[L]{Relatório Técnico}
      - \fancyhead[R]{OUVIDORIA/COATD}
      - \fancyfoot[C]{\thepage}

lang: pt-BR
fontsize: 11pt
linestretch: 1.3
mainfont: "TeX Gyre Pagella"

bibliography: "ABNT/referencias.bib"
csl: "ABNT/abnt.csl"