version: '3.8'

services:
  motor-processamento:
    image: motor-anonimizacao-base
    container_name: pipeline-processamento

    env_file:
      - .env

    volumes:
      - ../ABNT:/app/ABNT
      - ../_quarto.yml:/app/_quarto.yml
      - ../rme:/app/rme
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./outputs:/app/outputs

    working_dir: /app
    
    command: >
      bash -c "quarto render scripts/qmd/tratamento_falabr.qmd && mkdir -p outputs/pdf && mv scripts/qmd/*.pdf outputs/pdf/"