---
title: "Relatório Técnico: Pré-Processamento de Dados para Geoestatística - ANTT/OUVIDORIA/COATD"
subtitle: "Tratamento de Dados Sensíveis via Transformers e Regex"
author: 
  - name: "Pedro Muniz Cherulli"
    affiliation: "COATD - Coordenação de Análise e Tratamento de Dados"
date: today
date-format: "DD/MM/YYYY"
---

# **Introdução**

## **Objetivo do Relatório**

O presente relatório tem como objetivo detalhar o processo de anonimização de dados de manifestações recebidas pela **Ouvidoria** da **Agência Nacional de Transportes Terrestres** (ANTT). Por meio da aplicação de técnicas de **Processamento de Linguagem Natural** (PLN) e **Expressões Regulares** (Regex), buscamos garantir a privacidade dos dados sensíveis contidos nas mensagens, conforme é exigido pela @lgpd2018. Ao mesmo tempo, preservamos a integridade e a utilidade das informações para análises futuras.

## **Segurança e Arquitetura**

Um pilar fundamental deste projeto é o foco na privacidade dos cidadãos. Para evitar o risco de vazamento de dados inerente ao uso de APIs de terceiros e soluções em nuvem, toda a arquitetura deste pipeline foi desenhada para processamento estritamente local. Essa abordagem assegura total controle sobre o fluxo da informação e conformidade rigorosa com a LGPD, permitindo que a anonimização das manifestações seja feita em um ambiente seguro antes de qualquer eventual integração com outras plataformas analíticas.

## **Estrutura do Relatório**

A elaboração deste relatório seguiu uma estrutura lógica e sequencial, visando a clareza e a compreensão do processo de anonimização dos dados. A seguir, descrevemos as principais etapas e seções do relatório:

### **Carregamento e Conversão de Dados**

Nesta seção, realizamos a leitura dos arquivos Excel contendo as manifestações, convertendo-os para o formato CSV para facilitar o processamento subsequente. Caso o arquivo já esteja no formato CSV, o relatório reporta um "erro", informando que nenhum arquivo *.xlsx* foi encontrado.

```{python}
#| echo: false
#| label: importacao-bibliotecas

import pandas as pd
from IPython.display import Markdown, display
import seaborn as sns
import matplotlib.pyplot as plt
import re
import os
import requests
import spacy
import gc
import torch
import spacy_transformers
from transformers import AutoTokenizer
from datetime import datetime, timedelta
from dotenv import load_dotenv, find_dotenv
```

```{python}
#| echo: false
#| label: extracao-ids-api-falabr

load_dotenv(find_dotenv())
headers = {
    "Authorization": f"Bearer {os.getenv('TOKEN_API_OUVIDORIA')}", 
    "Accept": "application/json"
}

data_atual = datetime.strptime("01/01/2026", "%d/%m/%Y").date()
data_limite = datetime.strptime("01/01/2026", "%d/%m/%Y").date()
url_api = "https://falabr.cgu.gov.br/api/manifestacoes"

lista_ids = []

while data_atual <= data_limite:
    str_data = data_atual.strftime("%d/%m/%Y")

    print(f"Extraindo dados do dia: {str_data}")
    
    parametros = {
        "dataCadastroInicio": str_data,
        "dataCadastroFim": str_data
    }
    
    resposta = requests.get(url_api, headers=headers, params=parametros)
    
    if resposta.status_code == 200:
        dados = resposta.json()
        
        if dados:
            for item in dados:
                if "IdManifestacao" in item:
                    lista_ids.append(item["IdManifestacao"])
        
    data_atual += timedelta(days=1)

print(f"Extração concluída! {len(lista_ids)} IDs salvos na lista.")
```

```{python}
#| echo: false
#| label: salvar-ids

caminho_arquivo = "../../data/raw/txt/ids_manifestacoes.txt"

if os.path.exists(caminho_arquivo):
    os.remove(caminho_arquivo)

with open(caminho_arquivo, "w") as arquivo:
    for lista in lista_ids:
        arquivo.write(f"{lista}\n")
```

```{python}
#| include: false
#| label: extracao-detalhes-manifestacoes

dados_completos = []
contagem = 0

load_dotenv(find_dotenv())
headers = {
    "Authorization": f"Bearer {os.getenv('TOKEN_API_OUVIDORIA')}", 
    "Accept": "application/json"
}

with open("../../data/raw/txt/ids_manifestacoes.txt", "r") as arquivo:
    for linha in arquivo:
        id_manifestacao = linha.strip()
        url_detalhes = f"https://falabr.cgu.gov.br/api/manifestacoes/{id_manifestacao}"
        
        resposta = requests.get(url_detalhes, headers=headers)
        
        if resposta.status_code == 200:
            dados_completos.append(resposta.json())
            contagem += 1
            print(f"{contagem} manifestações processadas...")
            

dados_filtrados = []

for item in dados_completos:
    id_manifestacao = item.get("IdManifestacao")
    descricao = ((item.get("Teor") or {}).get("DescricaoAtosOuFatos") or {})

    linha_filtrada = {
        "id_mensagem": id_manifestacao,
        "descricao": descricao
    }
    
    dados_filtrados.append(linha_filtrada)

df = pd.DataFrame(dados_filtrados)

df_amostra = df.head(1)
display(Markdown(df_amostra.to_markdown(index=False)))
```

------------------------------------------------------------------------

# Análise Técnica do Projeto

## Análise Exploratória dos Dados

**Valores faltantes**, **tipos de dados**, **distribuição de categorias**, **moda por categoria** e outras características dos dados foram analisados para entender a estrutura e a qualidade dos dados antes do processo de anonimização.

```{python}
#| echo: false
#| label: tbl-resumo-dados
#| tbl-cap: "Dicionário de Dados e Qualidade das Variáveis"

linhas, colunas = df.shape
display(Markdown(f"**Dimensões do conjunto de dados:** {linhas} manifestações distribuídas em {colunas} variáveis.\n\n---"))

df_resumo = pd.DataFrame({
    "Tipo de Dado": df.dtypes.astype(str),
    "Valores Nulos": df.isnull().sum()
}).reset_index()

df_resumo.rename(columns={"index": "Variável"}, inplace=True)
display(Markdown(df_resumo.to_markdown(index=False)))
```

## Limpeza e Normalização de Texto

### O que é regex e como foi utilizado?

Expressões regulares `regex` são sequências de caracteres que formam um padrão de pesquisa. Elas são usadas para encontrar e manipular `strings` com base em padrões específicos. No processo de anonimização, regex foi utilizado para identificar e remover ou substituir informações sensíveis, como nomes de usuários, atendentes, e-mails, etc. Garantindo que os dados sejam limpos e normalizados antes da anonimização.

### Como a `regex` Funciona?

A regex é composta por uma combinação de caracteres literais e metacaracteres que definem o padrão de pesquisa. Por exemplo, `\d` representa um dígito, `\s` representa um espaço em branco, e \*\*.\*?\*\* representa qualquer sequência de caracteres (não gananciosa). Ao aplicar regex ao texto, ele procura por correspondências com o padrão definido e pode substituir ou remover essas correspondências conforme necessário.

```{python}
#| echo: false
#| label: tbl-padrao-usuario
#| tbl-cap: "Amostra de Mensagens Limpas"

df["descricao"] = df["descricao"].astype(str)
df["descricao"] = df["descricao"].str.replace(r'([^\w\s])(?:\s*\1)+', r'\1', regex=True)
df["descricao"] = df["descricao"].str.replace(r'\s+', ' ', regex=True).str.strip()

df_amostra = df.head(1)
display(Markdown(df_amostra.to_markdown(index=False)))
```

------------------------------------------------------------------------

## Anonimização de Dados com Regex

Nesta etapa, expressões regulares, `regex`, foram utilizadas para identificar e anonimizar informações sensíveis, como: **E-mails**, **URLs**, **Números de Manifestações**, **Telefone**, **CPF**, **CNPJ**, **RG**, **CEP** e **Placas (Padrões novos e Antigos)**. O processo de anonimização substitui essas informações por um espaço em branco.

-   Exemplos de regex para anonimização:
    -   `r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"` para identificar e anonimizar endereços de e-mail.
    -   `r"https?://?[^\s]+|www\.[^\s]+"` para identificar e anonimizar URLs.
    -   `r"\d{3}(?:[.\-/_\s]*)\d{3}(?:[.\-/_\s]*)\d{3}(?:[.\-/_\s]*)\d{2}"` para identificar e anonimizar CPFs.

```{python}
#| echo: false
#| label: tbl-resultado-anonimizacao-regex
#| tbl-cap: "Amostra de Mensagens Anonimizadas Utilizando Expressões Regulares (Regex)"

patterns = {
    "EMAIL": r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}",
    "URL": r'https?:\/{1,2}[^\s"<>]+|www\.[^\s"<>]+',
    "MANIFESTACAO": r"\d{5}(?:[.\-/_\s]*)\d{6}(?:[.\-/_\s]*)/?(?:[.\-/_\s]*)\d{4}(?:[.\-/_\s]*)\d{2}",
    "CNPJ": r"\d{2}(?:[.\-/_\s]*)\d{3}(?:[.\-/_\s]*)\d{3}(?:[.\-/_\s]*)(?:[.\-/_\s]*)\d{4}(?:[.\-/_\s]*)\d{2}",
    "CPF": r"\d{3}(?:[.\-/_\s]*)\d{3}(?:[.\-/_\s]*)\d{3}(?:[.\-/_\s]*)\d{2}",
    "PLACA": r"([A-Za-z]{3}[.\-/_\s]*\d{4})|([A-Za-z]{3}[.\-/_\s]*\d[.\-/_\s]*[A-Za-z][.\-/_\s]*\d{2})",
    "TELEFONE": r"(?:\+?55[.\-/_\s]*)?(?:\(?\d{2}\)?[.\-/_\s]*)?(?:9[.\-/_\s]*)?\d{4}[.\-/_\s]*\d{4}",
    "RG": r"\d{1,3}(?:[.\-_\s]*)\d{3}(?:[.\-_\s]*)\d{2,3}(?:[.\-_\s]*)[\dXx]",
    "CEP": r"\d{5}(?:[.\-/_\s]*)\d{3}",
    "REDACTED": r"\d{6,}"
}

compiled_patterns = [re.compile(rf"\S*(?:{p})\S*", flags=re.IGNORECASE) for p in patterns.values()]

def anonimizar_regex(texto):
    texto = str(texto)
    for regex in compiled_patterns:
        texto = regex.sub("[ANONIMIZADO]", texto)
    return re.sub(r"\s+", " ", texto).strip()

df_anonimizado = df.copy()
df_anonimizado["descricao_anonimizada"] = df["descricao"].apply(anonimizar_regex).str.strip()

df_amostra = df_anonimizado[["descricao_anonimizada"]].head(1)

display(Markdown(df_amostra.to_markdown(index=False)))
```

------------------------------------------------------------------------

### **Divisão de Mensagens em Partes**

Devido à limitação de tokens para processamento em modelos de linguagem, as mensagens foram divididas em partes menores, garantindo que cada parte não exceda o limite de **256 tokens**. A segmentação sintática foi realizada com *SpaCy*, enquanto o controle de limite foi feito com tokenização compatível com o modelo *BERT*.

```{python}
#| echo: false
#| label: tbl-resultado-divisao
#| tbl-cap: "Amostra de Mensagens Divididas em Partes"

nlp = spacy.load("pt_core_news_lg", disable=["ner", "lemmatizer", "textcat", "parser", "attribute_ruler"])
if "sentencizer" not in nlp.pipe_names:
    nlp.add_pipe("sentencizer")

tokenizer = AutoTokenizer.from_pretrained("neuralmind/bert-base-portuguese-cased")

def contar_tokens_bert(texto):
    return len(tokenizer.encode(texto, add_special_tokens=False, truncation=False))

def preparar_base(df, col_texto, nlp, limite_tokens=256):
    dados_finais = []
    textos_com_ids = zip(df[col_texto].astype(str), df['id_mensagem'])
    
    for doc, id_original in nlp.pipe(textos_com_ids, batch_size=100, as_tuples=True):
        id_unico = id_original

        chunk_atual = []
        tokens_acumulados = 0
        ordem = 1

        if not doc.text.strip():
            dados_finais.append({
                'id_mensagem': id_unico,
                'ordem_parte': 1,
                'descricao_anonimizada': ""
            })
            continue
        
        for sent in doc.sents:
            qtd_tokens_sent = contar_tokens_bert(sent.text)

            if qtd_tokens_sent > limite_tokens:
                if chunk_atual:
                      dados_finais.append({
                          'id_mensagem': id_unico,
                          'ordem_parte': ordem,
                          'descricao_anonimizada': " ".join([sent.text for sent in chunk_atual]).strip()
                      })
                      ordem += 1
                      chunk_atual = []
                      tokens_acumulados = 0
                  
                tokens_bert = tokenizer.encode(sent.text, add_special_tokens=False)
                    
                for i in range(0, len(tokens_bert), limite_tokens):
                    chunk_ids = tokens_bert[i : i + limite_tokens]
                    chunk_text = tokenizer.decode(chunk_ids)
                      
                    dados_finais.append({
                        'id_mensagem': id_unico,
                        'ordem_parte': ordem,
                        'descricao_anonimizada': chunk_text.strip()
                    })
                    ordem += 1
                continue

            if tokens_acumulados + qtd_tokens_sent > limite_tokens:
                dados_finais.append({
                    'id_mensagem': id_unico,
                    'ordem_parte': ordem,
                    'descricao_anonimizada': " ".join([sent.text for sent in chunk_atual]).strip()
                })
                ordem += 1
                chunk_atual = [sent]
                tokens_acumulados = qtd_tokens_sent
            else:
                chunk_atual.append(sent)
                tokens_acumulados += qtd_tokens_sent

        if chunk_atual:
            dados_finais.append({
                'id_mensagem': id_unico,
                'ordem_parte': ordem,
                'descricao_anonimizada': " ".join([sent.text for sent in chunk_atual]).strip()
            })
            
    return pd.DataFrame(dados_finais)

df_final = preparar_base(df_anonimizado, col_texto='descricao_anonimizada', nlp=nlp)

df_amostra = df_final["descricao_anonimizada"].loc[
    df_final["descricao_anonimizada"].str.contains("[ANONIMIZADO]", regex=False, na=False)
].head(1)

display(Markdown(df_amostra.to_markdown(index=False)))
```

------------------------------------------------------------------------

### **Anonimização com Modelo de Reconhecimento de Entidades Nomeadas**

Para aprimorar a anonimização, foi utilizado um modelo de **Reconhecimento de Entidades Nomeadas** (NER) treinado especificamente para identificar e substituir entidades sensíveis nas mensagens. O modelo foi carregado e aplicado às mensagens divididas, garantindo uma anonimização mais precisa e contextualizada.

```{python}
#| echo: false
#| warning: false
#| label: tbl-resultado-ner
#| tbl-cap: "Amostra de Mensagens Anonimizadas Utilizando Modelo de Reconhecimento de Entidades Nomeadas (NER)"

os.environ["TOKENIZERS_PARALLELISM"] = "false"

gc.collect()

num_threads = max(1, os.cpu_count() - 1)
torch.set_num_threads(num_threads)

caminho_modelo = r"../../models/v1_modelo_inicial/model-best"
nlp_custom = spacy.load(caminho_modelo)

def anonimizar_doc(doc):
    texto = doc.text
    
    entidades = sorted(doc.ents, key=lambda e: e.start_char, reverse=True)
    
    for ent in entidades:
        mascara = f" [{ent.label_}] "
        texto = texto[:ent.start_char] + mascara + texto[ent.end_char:]
        
    return re.sub(r"\s+", " ", texto).strip()
  
textos = df_final["descricao_anonimizada"].astype(str).tolist()
textos_anonimizados = []
for doc in nlp_custom.pipe(textos, batch_size=8):
    textos_anonimizados.append(anonimizar_doc(doc))
    
    if len(textos_anonimizados) % 500 == 0:
        print(f"Processadas {len(textos_anonimizados)} mensagens...")

df_final["texto_final_anonimizado"] = textos_anonimizados

df_amostra = df_final["texto_final_anonimizado"].loc[
    df_final["texto_final_anonimizado"].str.contains("[ANONIMIZADO]", regex=False, na=False)
].head(1)

display(Markdown(df_amostra.to_markdown(index=False)))
```

------------------------------------------------------------------------

### **Reconstrução das Mensagens Anonimizadas**

Após a aplicação do modelo NER, as mensagens foram reconstruídas a partir das partes divididas, preservando a utilidade analítica do texto. As mensagens reconstruídas foram então exportadas para os **formatos Excel e CSV**, facilitando o acesso e a utilização dos dados anonimizados para análises futuras.

```{python}
#| echo: false
#| label: tbl-reconstruido
#| tbl-cap: "Amostra de Mensagens Reconstruídas Após Anonimização e Divisão em Partes"

df_final = df_final.sort_values(by=['id_mensagem', 'ordem_parte'])

df_reconstruido = df_final.groupby('id_mensagem')['texto_final_anonimizado'].apply(' '.join).reset_index()
df_reconstruido["texto_final_anonimizado"] = df_reconstruido["texto_final_anonimizado"].str.replace(r'\s+', ' ', regex=True).str.strip()

df_reconstruido.to_excel("../../data/processed/xlsx/data_anonimizado.xlsx", index=False)
df_reconstruido.to_csv("../../data/processed/csv/data_anonimizado.csv", index=False, sep=";")

display(Markdown(df_reconstruido["texto_final_anonimizado"].head(1).to_markdown(index=False)))
```

### **Análise de Resultados**

Análise da distribuição da quantidade de entidades anonimizadas por mensagem revelou insights importantes sobre a natureza dos dados e a eficácia do processo de anonimização. A visualização dessa distribuição permitiu identificar padrões e tendências sobre a performance das **Expressões Regulares** e Modelo **NER** no processo de anonimização de dados.

```{python}
#| echo: false
#| warning: false
#| label: fig-distribuicao-anonimizacoes
#| fig-cap: "Distribuição da Quantidade de Entidades Anonimizadas por Mensagem"

df_reconstruido["contagem_anonimizacoes"] = df_reconstruido["texto_final_anonimizado"].str.count(r"\[(?:ANONIMIZADO|NOME|EMPRESA|ENDERECO)\]")
plt.figure(figsize=(10, 6))
sns.histplot(df_reconstruido["contagem_anonimizacoes"], bins=30, kde=False, color="forestgreen")
plt.xlabel("Quantidade de Anonimizacoes")
plt.ylabel("Número de Mensagens")
plt.grid(axis="y", alpha=0.75)
plt.show()
```

```{python}
#| echo: false
#| output: asis

total_mensagens = len(df_final['id_mensagem'].unique())
total_anonimizacoes = df_reconstruido["contagem_anonimizacoes"].sum()

texto_impacto = f"""
Neste ciclo de processamento, o pipeline analisou com sucesso **{total_mensagens}** manifestações, identificando e mascarando um total de **{total_anonimizacoes}** entidades sensíveis.
"""
display(Markdown(texto_impacto))
```

------------------------------------------------------------------------

# **Conclusão**

O processo de anonimização de dados utilizando técnicas de **PLN** e **Regex** demonstrou ser eficaz na proteção da privacidade das informações sensíveis contidas nas manifestações recebidas pela Ouvidoria da ANTT. A combinação de **Expressões Regulares** para identificação de padrões específicos e o uso de um modelo **NER** treinado permitiu uma anonimização mais precisa e contextualizada, garantindo a integridade e a utilidade dos dados para análises futuras.

## **Trabalhos Futuros e Próximos Passos**

Embora os resultados atuais demonstrem a eficácia da abordagem metodológica adotada, a evolução da ferramenta prevê as seguintes etapas:

- **Aprimoramento Contínuo do NER:** Realização de novos ciclos de treinamento com bases de dados expandidas para aumentar o *recall* do modelo e mapear exceções e variações linguísticas emergentes.

- **Adequação da Infraestrutura Computacional:** Devido à altíssima demanda de processamento exigida pelos modelos baseados em Transformers (*Deep Learning*), torna-se imperativa a melhoria do parque tecnológico. A aquisição de estações de trabalho equipadas com aceleração gráfica dedicada de alta performance será fundamental para garantir que o pipeline processe a carga de meio milhão de registros anuais localmente em tempo hábil.

------------------------------------------------------------------------

# **Referências**
