services:
  motor-rotulacao:
    image: motor-anonimizacao-base
    container_name: pipeline-rotulacao
    
    ports:
      - "5000:5000"   # Rotulador
      - "4200:4200"   # Dashboard Quarto

    volumes:
      - ../ner:/app/ner
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./outputs:/app/outputs
      - ./start.sh:/app/start.sh

    working_dir: /app
    
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1

    command: ["bash", "start.sh"]